server:
  port: 8080
  servlet:
    context-path: /product-service
spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/products
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:9296
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}